package arm

import (
	"fmt"
	"sort"
	"strings"
)

// emitRustInsnTests generates a round-trip test per typed form: encode with the
// typed method, then decode the word with the table-driven decoder and require
// it to name the encoding the method was generated from.
//
// The decoder is an independent check — it comes from the bit patterns, not from
// the operand model — so a mis-placed field shows up as a decode mismatch rather
// than passing because both sides share a bug.
func emitRustInsnTests(s *AsmSurface) string {
	var b strings.Builder
	b.WriteString("// Generated by mkasm — do not edit.\n//\n")
	b.WriteString("// Encode/decode round-trip for every typed instruction method.\n\n")
	b.WriteString("use crate::asm_support::*;\nuse crate::decoders;\nuse crate::insns::*;\n\n")

	type testCase struct {
		name string
		body string
	}
	var cases []testCase
	skipped := 0
	// One encoding can reach the same method twice when ARM writes a register's
	// width as a specifier and the form expands per width, so names are unique.
	usedTestNames := map[string]bool{}

	for _, name := range s.MethodOrder {
		// Resolve names through the same grouping the emitter uses, so a form in
		// a suffixed arity variant is called by the name it actually has.
		for _, g := range GroupByArity(name, s.Methods[name]) {
			// Mirror the emitter's per-arity tuple dedup. If two forms of one
			// mnemonic reach the same signature, only the first gets an impl, and
			// a test for the second would call the first's encoding and blame the
			// wrong instruction for the mismatch.
			claimed := map[string]bool{}
			for _, f := range g.Forms {
				f.RequiredArity = g.Arity
				n := g.Arity
				if n > len(f.Params) {
					n = len(f.Params)
				}
				if tuple := tupleType(f.Params[:n]); claimed[tuple] {
					skipped++
					continue
				} else {
					claimed[tuple] = true
				}
				args, ok := sampleArgs(f)
				if !ok {
					skipped++
					continue
				}
				method := g.Method
				cases = append(cases, testCase{
					name: uniqueName(rustTestName(g.Method, f.EncodingID), usedTestNames),
					body: fmt.Sprintf(`    let mut a = Assembler::new();
    a.%s(%s);
    assert!(a.error().is_none(), "%s: {:?}", a.error());
    let w = a.words()[0];
    let d = decoders::decode(w).unwrap_or_else(|e| panic!("%s: 0x{w:08X} did not decode: {e:?}"));
    assert!(
        d.encoding_id == %q || d.ambiguous.contains(&%q),
        "%s: 0x{w:08X} decoded as {} (ambiguous {:?})",
        d.encoding_id,
        d.ambiguous
    );`,
						method, args, f.EncodingID, f.EncodingID,
						f.EncodingID, f.EncodingID, f.EncodingID),
				})
			}
		}
	}

	sort.Slice(cases, func(i, j int) bool { return cases[i].name < cases[j].name })
	for _, c := range cases {
		fmt.Fprintf(&b, "#[test]\nfn %s() {\n%s\n}\n\n", c.name, c.body)
	}

	fmt.Fprintf(&b, "// %d typed forms covered; %d skipped for want of a sample operand value.\n",
		len(cases), skipped)
	b.WriteString(emitExactEncoderTests(s))
	b.WriteString(emitRawEncoderTests(s))
	return b.String()
}

// emitExactEncoderTests round-trips every encoding through its exact encoder.
//
// The typed methods cover the encodings whose operands could be typed; this
// covers all of them, which is what makes "every encoding in the spec" a checked
// claim rather than a count of generated functions. A zero-field word is decoded
// back only when it satisfies the encoding's bitdiff constraints; every encoder
// is independently cross-checked against the table encoder with non-zero fields.
func emitExactEncoderTests(s *AsmSurface) string {
	var b strings.Builder
	b.WriteString(`
// --- exact encoders: every encoding in the spec ---------------------------

// xchk compares a generated exact encoder against the table-driven encoder.
//
// The two are built from the same field table but by different code: one emits
// a function with the bit positions inlined, the other looks them up at run
// time. Agreeing on non-zero field values is what shows the inlined positions
// are right — decoding a word built from all-zero fields would not.
fn xchk(bad: &mut Vec<String>, id: &'static str, fields: &[(&str, u64)], got: u32) {
    match crate::encoders::encode_with_fields(id, fields) {
        Ok(want) if want == got => {}
        Ok(want) => bad.push(format!("{id}: exact encoder gave 0x{got:08X}, table gave 0x{want:08X}")),
        Err(e) => bad.push(format!("{id}: table encoder failed: {e:?}")),
    }
}

fn chk(bad: &mut Vec<String>, id: &'static str, alias_of: &'static str, w: u32) {
    match decoders::decode(w) {
        Ok(d) => {
            // An alias encodes to the same word as the instruction it stands for,
            // so the decoder naming the canonical form is a correct answer.
            if d.encoding_id != id && d.encoding_id != alias_of && !d.ambiguous.contains(&id) {
                bad.push(format!("{id}: 0x{w:08X} decoded as {}", d.encoding_id));
            }
        }
        Err(e) => bad.push(format!("{id}: 0x{w:08X} did not decode: {e:?}")),
    }
}

`)
	const perTest = 200
	for i := 0; i < len(s.Exact); i += perTest {
		end := i + perTest
		if end > len(s.Exact) {
			end = len(s.Exact)
		}
		fmt.Fprintf(&b, "#[test]\nfn exact_encoders_%04d() {\n    let mut bad: Vec<String> = Vec::new();\n", i/perTest)
		for _, e := range s.Exact[i:end] {
			args := make([]string, 0, len(e.Fields))
			for range e.Fields {
				args = append(args, "0")
			}
			if e.FixedLegal {
				fmt.Fprintf(&b, "    chk(&mut bad, %q, %q, { let mut a = Assembler::new(); a.%s(%s); a.words()[0] });\n",
					e.EncodingID, e.AliasOf, e.Fn, strings.Join(args, ", "))
			}

			// Same encoder again with a distinct value per field, cross-checked
			// against the table-driven encoder. A field written at the wrong
			// offset, or with another field's width, shows up here.
			vals := make([]string, 0, len(e.Fields))
			pairs := make([]string, 0, len(e.Fields))
			for k, f := range e.Fields {
				shift := freeLowBit(f.Free, f.Start)
				// Within the bits the encoding leaves free, so the value is
				// representable and both encoders must agree on where it lands.
				v := uint32(k*7+1) & (f.Free >> uint(shift))
				vals = append(vals, fmt.Sprintf("%d", v))
				// The table encoder takes the whole field, so the pinned bits of
				// this encoding are put back before comparing.
				fieldMask := fieldRangeMask(f.Start, f.End)
				full := (e.FixedWord&fieldMask&^f.Free | (v<<uint(shift))&f.Free) >> uint(f.Start)
				pairs = append(pairs, fmt.Sprintf("(%q, %d)", f.Name, full))
			}
			fmt.Fprintf(&b, "    xchk(&mut bad, %q, &[%s], { let mut a = Assembler::new(); a.%s(%s); a.words()[0] });\n",
				e.EncodingID, strings.Join(pairs, ", "), e.Fn, strings.Join(vals, ", "))
		}
		b.WriteString("    assert!(bad.is_empty(), \"{} exact encoders wrong:\\n{}\", bad.len(), bad.join(\"\\n\"));\n}\n\n")
	}
	fmt.Fprintf(&b, "// %d exact encoders covered.\n", len(s.Exact))
	return b.String()
}

// emitRawEncoderTests cross-checks the dynamic fallback used by encodings that
// have no operand-typed signature. In particular, this catches writes through
// partially pinned fields: the raw API must preserve the encoding's fixed bits
// exactly as the table-driven encoder does.
func emitRawEncoderTests(s *AsmSurface) string {
	var b strings.Builder
	b.WriteString(`
// --- raw fallback: every untyped encoding ---------------------------------

`)
	const perTest = 100
	for i := 0; i < len(s.Raw); i += perTest {
		end := i + perTest
		if end > len(s.Raw) {
			end = len(s.Raw)
		}
		fmt.Fprintf(&b, "#[test]\nfn raw_encoders_%04d() {\n    let mut bad: Vec<String> = Vec::new();\n", i/perTest)
		for _, r := range s.Raw[i:end] {
			u32Fields := make([]string, 0, len(r.Fields))
			u64Fields := make([]string, 0, len(r.Fields))
			for k, f := range r.Fields {
				shift := freeLowBit(f.Free, f.Start)
				v := uint32(k*7+1) & (f.Free >> uint(shift))
				fieldMask := fieldRangeMask(f.Start, f.End)
				full := (r.FixedWord&fieldMask&^f.Free | (v<<uint(shift))&f.Free) >> uint(f.Start)
				u32Fields = append(u32Fields, fmt.Sprintf("(%q, %d)", f.Name, full))
				u64Fields = append(u64Fields, fmt.Sprintf("(%q, %du64)", f.Name, full))
			}
			fmt.Fprintf(&b, `    {
        let mut a = Assembler::new();
        match a.emit_raw(%q, &[%s]) {
            Ok(()) => match crate::encoders::encode_with_fields(%q, &[%s]) {
                Ok(want) if a.words() == &[want] => {}
                Ok(want) => bad.push(format!(%q, a.words())),
                Err(e) => bad.push(format!(%q)),
            },
            Err(e) => bad.push(format!(%q)),
        }
    }
`,
				r.EncodingID, strings.Join(u32Fields, ", "),
				r.EncodingID, strings.Join(u64Fields, ", "),
				r.EncodingID+": raw fallback gave {:?}, table gave 0x{want:08X}",
				r.EncodingID+": table encoder failed: {e}",
				r.EncodingID+": raw fallback failed: {e}",
			)
		}
		b.WriteString("    assert!(bad.is_empty(), \"{} raw encoders wrong:\\n{}\", bad.len(), bad.join(\"\\n\"));\n}\n\n")
	}
	fmt.Fprintf(&b, "// %d raw fallback encoders covered.\n", len(s.Raw))
	return b.String()
}

// rustTestName includes the method because one encoding can be reachable from
// two methods: its required arity and its full arity with optional operands.
func rustTestName(method, encodingID string) string {
	var b strings.Builder
	b.WriteString("rt_")
	b.WriteString(method)
	b.WriteByte('_')
	for _, r := range encodingID {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + 32)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// sampleArgs builds a legal call for one form. ok is false when any operand has
// no value this generator can justify, in which case no test is emitted rather
// than a guessed one.
func sampleArgs(f AsmForm) (string, bool) {
	n := f.RequiredArity
	if n > len(f.Params) {
		n = len(f.Params)
	}
	if n == 0 {
		return "", true
	}
	args := make([]string, 0, n)
	// Arrangement bits already committed to by an earlier operand.
	chosen := map[uint32]uint32{}
	for i := 0; i < n; i++ {
		v, ok := sampleValue(f.Params[i], f, i, n, chosen)
		if !ok {
			return "", false
		}
		args = append(args, v)
	}
	return strings.Join(args, ", "), true
}

// sampleValue picks a legal Rust literal for one operand. Register numbers vary
// by position so a field swapped with its neighbour changes the word.
func sampleValue(p Param, f AsmForm, idx, arity int, chosen map[uint32]uint32) (string, bool) {
	reg := idx + 1 // 1, 2, 3 … keeps positions distinguishable

	// A sized operand needs an arrangement this encoding actually allows, and one
	// that selects the same bits as the operand already driving those bits —
	// otherwise the generated call trips the arrangement-consistency check.
	if p.ArrDispatch != nil && len(p.ArrDispatch.Cases) > 0 {
		c := p.ArrDispatch.Cases[0]
		if want, ok := chosen[p.ArrDispatch.Mask]; ok {
			found := false
			for _, alt := range p.ArrDispatch.Cases {
				if alt.Or == want {
					c, found = alt, true
					break
				}
			}
			if !found {
				return "", false
			}
		} else {
			chosen[p.ArrDispatch.Mask] = c.Or
		}
		arr := strings.ToLower(arrangementIdent(c.Symbol))
		switch p.Class {
		case ClassSimdVec:
			return fmt.Sprintf("V%d.%s()", sampleReg(p, reg), arr), true
		case ClassSveZ:
			return fmt.Sprintf("Z%d.%s()", sampleReg(p, reg), arr), true
		case ClassSveP:
			return fmt.Sprintf("P%d.%s()", sampleReg(p, reg%8), arr), true
		case ClassSvePN:
			return fmt.Sprintf("PnReg::new(%d).%s()", sampleReg(p, reg), arr), true
		case ClassSmeTile:
			return fmt.Sprintf("ZA%d.%s()", sampleReg(p, 0), arr), true
		}
	}
	if p.Class == ClassEnum {
		// The first spelling this encoding accepts, taken from its own table
		// rather than from the shared type, which may name more.
		for _, d := range f.Enums {
			if d.Param == p.Name && len(d.Cases) > 0 {
				pick := 0
				// When the same form has an optional continuation, exercise a
				// different legal enum row in the full-arity call.  This is
				// essential for value-dependent grammars such as `IC`: whole-
				// cache operations omit Xt, while IVAU consumes it.
				hasOptionalRegister := false
				for i := 0; i < arity && i < len(f.Params); i++ {
					hasOptionalRegister = hasOptionalRegister ||
						(f.Params[i].Optional && registerClass(f.Params[i].Class))
				}
				if hasOptionalRegister {
					pick = len(d.Cases) - 1
				}
				return d.Type + "::" + enumVariantIdent(d.Cases[pick].Symbol), true
			}
		}
		return "", false
	}
	switch p.Class {
	case ClassSveZ:
		return fmt.Sprintf("Z%d", sampleReg(p, reg)), true
	case ClassSveP:
		return fmt.Sprintf("P%d", sampleReg(p, reg%8)), true
	case ClassSvePN:
		return fmt.Sprintf("PnReg::new(%d)", sampleReg(p, reg)), true
	case ClassSmeTile:
		return fmt.Sprintf("ZA%d", sampleReg(p, 0)), true
	case ClassGpr32:
		return fmt.Sprintf("W%d", sampleReg(p, reg)), true
	case ClassGpr64:
		return fmt.Sprintf("X%d", sampleReg(p, reg)), true
	case ClassGpr32Sp:
		return fmt.Sprintf("WSpReg::new(%d)", sampleReg(p, reg)), true
	case ClassGpr64Sp:
		if p.RustType == "Mem" {
			return sampleMem(f)
		}
		return fmt.Sprintf("XSpReg::new(%d)", sampleReg(p, reg)), true
	case ClassSimdB:
		return fmt.Sprintf("B%d", sampleReg(p, reg)), true
	case ClassSimdH:
		return fmt.Sprintf("H%d", sampleReg(p, reg)), true
	case ClassSimdS:
		return fmt.Sprintf("S%d", sampleReg(p, reg)), true
	case ClassSimdD:
		return fmt.Sprintf("D%d", sampleReg(p, reg)), true
	case ClassSimdQ:
		return fmt.Sprintf("Q%d", sampleReg(p, reg)), true
	case ClassSimdVec:
		return fmt.Sprintf("V%d", sampleReg(p, reg)), true
	case ClassCond:
		return "Cond::Eq", true
	case ClassLabel:
		return "0", true
	case ClassShift:
		return "Shift::Lsl(0)", true
	case ClassExtend:
		if len(p.Choices) > 0 {
			return "Extend::" + enumVariantIdent(p.Choices[0].Symbol), true
		}
		return "Extend::Uxtb", true
	case ClassSysReg:
		return "SysReg(0)", true
	case ClassFpImm:
		// 0x70 is the architectural compact encoding of 1.0.
		return "FpImm8::from_bits(0x70)", true
	case ClassImm:
		return sampleImm(p)
	}
	if p.RustType == "Mem" {
		return sampleMem(f)
	}
	return "", false
}

// sampleReg picks a register number this operand position actually accepts.
//
// A multi-vector group base is written as a multiple of the group size, and an
// SME select register starts at W12, so the obvious "register number = operand
// index" would produce calls the assembler rightly rejects.
func sampleReg(p Param, want int) int {
	scale := int(p.Scale)
	if scale < 1 {
		scale = 1
	}
	lo, hi := 0, 31
	if len(p.RegRanges) > 0 {
		lo, hi = int(p.RegRanges[0].Lo), int(p.RegRanges[0].Hi)
	}
	if p.HasRegRange {
		lo, hi = int(p.RegLo), int(p.RegHi)
	}
	if scale > 1 {
		// Only offsets that divide exactly are encodable.
		hi -= hi % scale
		v := lo + scale
		if v > hi {
			v = lo
		}
		return v
	}
	v := lo + want
	if v > hi {
		v = lo
	}
	if p.RegMultiple > 1 {
		m := int(p.RegMultiple)
		if rem := v % m; rem != 0 {
			v += m - rem
		}
		if v > hi {
			v = lo + (m-lo%m)%m
		}
	}
	return v
}

// sampleImm picks a value inside ARM's stated range that the field can hold.
func sampleImm(p Param) (string, bool) {
	scale := p.Scale
	if scale < 1 {
		scale = 1
	}
	if p.HasRange {
		// Inside ARM's range and a multiple of the scale. SYSP restricts its
		// CRn operand to C8-C9, so a value chosen for being small rather than
		// for being in range is rejected by the encoder that is under test.
		v := p.Lo
		if r := v % scale; r != 0 {
			v += scale - r
		}
		// Prefer a non-zero value where the range allows one, so a field left
		// unwritten is visible in the round trip.
		if v == 0 && scale <= p.Hi {
			v = scale
		}
		if v > p.Hi {
			v = p.Lo
		}
		return fmt.Sprintf("%d", v), true
	}
	return "0", true
}

// sampleMem builds a memory operand in a mode the form actually encodes.
func sampleMem(f AsmForm) (string, bool) {
	mode := f.Mode
	if len(f.ModeVariants) > 0 {
		mode = f.ModeVariants[0].Mode
	}
	switch mode {
	case AddrBase:
		return "Mem::base(XSpReg::new(20))", true
	case AddrOffset:
		return "Mem::offset(XSpReg::new(20), 0)", true
	case AddrPre:
		return "Mem::pre(XSpReg::new(20), 0)", true
	case AddrPost:
		return "Mem::post(XSpReg::new(20), 0)", true
	}
	return "", false
}
