package arm

import (
	"fmt"
	"sort"
	"strings"
)

// emitRustInsns renders the typed assembler surface: one trait per mnemonic, one
// impl per operand shape, and one flat-parameter method that forwards to it.
//
// Flat parameters with a tuple trait bound are what keep the call site readable:
//
//	pub fn add<A, B, C>(&mut self, a: A, b: B, c: C) where (A, B, C): AddArgs
//
// so `asm.add(X0, X1, 8)` type-checks, and a second impl on
// `(WReg, WReg, u32)` gives the 32-bit form the same method name.
func emitRustInsns(s *AsmSurface) string {
	var b strings.Builder
	b.WriteString("// Generated by mkasm — do not edit.\n//\n")
	b.WriteString("// Typed instruction methods. Each mnemonic gets one trait whose impls are\n")
	b.WriteString("// its operand shapes, so one method name covers every form ARM defines.\n\n")
	b.WriteString("#![allow(clippy::too_many_arguments)]\n\n")
	b.WriteString("use crate::asm_support::*;\n\n")
	b.WriteString(emitArrangementEnum(s))
	b.WriteString(emitEnumTypes(s))

	var traits strings.Builder
	var methods strings.Builder

	for _, name := range s.MethodOrder {
		forms := s.Methods[name]
		if len(forms) == 0 {
			continue
		}
		emitMethodGroup(&traits, &methods, name, forms)
	}

	b.WriteString(traits.String())
	b.WriteString("\nimpl Assembler {\n")
	b.WriteString(methods.String())
	b.WriteString("}\n")
	return b.String()
}

// ArityGroup is the set of forms sharing one method name: Rust cannot overload
// on parameter count, so each distinct arity of a mnemonic gets its own method.
type ArityGroup struct {
	Method string
	Arity  int
	Forms  []AsmForm
}

// GroupByArity buckets a mnemonic's forms into the methods that will be emitted.
//
// A form with optional trailing operands appears in two buckets — its required
// arity and its full arity — so `add(rd, rn, imm)` and
// `add_shift(rd, rn, imm, shift)` are both reachable.
//
// The bare mnemonic goes to the bucket holding the most forms rather than the
// smallest arity: `LDR` has a dozen two-operand forms and one one-operand SME
// form, and the SME outlier must not claim the name `ldr`.
//
// Both the instruction emitter and the test emitter resolve names here so they
// cannot drift apart.
func GroupByArity(name string, forms []AsmForm) []ArityGroup {
	byArity := map[int][]AsmForm{}
	for _, f := range forms {
		byArity[f.RequiredArity] = append(byArity[f.RequiredArity], f)
		if full := len(f.Params); full != f.RequiredArity {
			byArity[full] = append(byArity[full], f)
		}
	}
	arities := make([]int, 0, len(byArity))
	for a := range byArity {
		arities = append(arities, a)
	}
	// The bare mnemonic goes to the bucket with the most base-ISA forms, then to
	// the one with the most forms overall, then to the lowest arity. Counting
	// base-ISA forms first is what keeps `adr` meaning "ADR <Xd>, <label>"
	// rather than the four-operand SVE ADR, and counting forms at all is what
	// stops a one-operand SME LDR from claiming `ldr`.
	baseCount := func(fs []AsmForm) int {
		n := 0
		for _, f := range fs {
			if f.BaseISA {
				n++
			}
		}
		return n
	}
	sort.Slice(arities, func(i, j int) bool {
		bi, bj := baseCount(byArity[arities[i]]), baseCount(byArity[arities[j]])
		if bi != bj {
			return bi > bj
		}
		li, lj := len(byArity[arities[i]]), len(byArity[arities[j]])
		if li != lj {
			return li > lj
		}
		return arities[i] < arities[j]
	})

	used := map[string]bool{}
	out := make([]ArityGroup, 0, len(arities))
	for i, arity := range arities {
		group := byArity[arity]
		method := name
		if i > 0 {
			method = suffixedName(name, group[0], arity, used)
		}
		used[method] = true
		out = append(out, ArityGroup{Method: method, Arity: arity, Forms: group})
	}
	return out
}

// coercibleTo lists the operand types a position also accepts. ARM types
// "register or stack pointer" positions as their own class, but callers write
// plain X and W registers there, so those coerce.
func coercibleTo(rustType string) []string {
	switch rustType {
	case "XSpReg":
		return []string{"XReg"}
	case "WSpReg":
		return []string{"WReg"}
	case "Label":
		// A branch target is written as a byte offset or as a bound label.
		return []string{"i64", "LabelId"}
	}
	return nil
}

// tupleVariants enumerates the Self types to implement for one operand shape:
// the exact types plus every combination of their coercions. Capped so a form
// with many coercible positions cannot explode the generated crate.
func tupleVariants(params []Param) [][]string {
	const maxVariants = 8
	variants := [][]string{{}}
	for _, p := range params {
		alts := append([]string{p.RustType}, coercibleTo(p.RustType)...)
		next := make([][]string, 0, len(variants)*len(alts))
		for _, v := range variants {
			for _, a := range alts {
				if len(next) >= maxVariants {
					break
				}
				next = append(next, append(append([]string{}, v...), a))
			}
		}
		variants = next
	}
	return variants
}

func tupleOf(ts []string) string {
	if len(ts) == 0 {
		return "()"
	}
	if len(ts) == 1 {
		return "(" + ts[0] + ",)"
	}
	return "(" + strings.Join(ts, ", ") + ")"
}

// emitMethodGroup writes the trait, its impls, and the Assembler methods for one
// mnemonic.
func emitMethodGroup(traits, methods *strings.Builder, name string, forms []AsmForm) {
	for _, g := range GroupByArity(name, forms) {
		traitName := rustTraitName(g.Method)
		fmt.Fprintf(traits, "/// Operand shapes accepted by [`Assembler::%s`].\npub trait %s {\n    #[doc(hidden)]\n    fn emit_into(self, a: &mut Assembler);\n}\n\n",
			g.Method, traitName)

		// Distinct Self types only: two forms of one mnemonic can share a
		// parameter tuple after optional operands are trimmed, and Rust rejects
		// duplicate impls.
		seen := map[string]bool{}
		// Pass 1: the exact operand types of every form. These must be claimed
		// before any coercion, or `mov(X0, X1)` would land on MOV-from-SP's
		// coerced (XReg, XReg) instead of MOV-register's own encoding.
		for _, f := range g.Forms {
			if g.Arity > len(f.Params) {
				continue
			}
			params := f.Params[:g.Arity]
			if key := tupleType(params); !seen[key] {
				seen[key] = true
				emitFormImpl(traits, traitName, g.Method, f, g.Arity)
			}
		}
		// Pass 2: coercions, so callers can pass X0 where ARM types the position
		// as "register or SP", and a plain integer where it expects a branch
		// target. Only tuples no form claimed outright.
		for _, f := range g.Forms {
			if g.Arity > len(f.Params) {
				continue
			}
			params := f.Params[:g.Arity]
			for _, v := range tupleVariants(params) {
				key := tupleOf(v)
				if seen[key] {
					continue
				}
				seen[key] = true
				emitCoercionImpl(traits, traitName, params, v)
			}
		}
		emitMethod(methods, g.Method, traitName, g.Forms[0], g.Arity)
	}
}

// suffixedName names a higher-arity variant after the operands it adds.
func suffixedName(base string, f AsmForm, arity int, used map[string]bool) string {
	var extra []string
	for i := 0; i < arity && i < len(f.Params); i++ {
		extra = append(extra, f.Params[i].Name)
	}
	// Name after the trailing operands that distinguish this variant.
	tail := ""
	if len(extra) > 0 {
		tail = extra[len(extra)-1]
	}
	cand := base
	if tail != "" {
		cand = base + "_" + tail
	}
	if cand == base || used[cand] {
		cand = fmt.Sprintf("%s_%d", base, arity)
	}
	for used[cand] {
		cand += "_"
	}
	return cand
}

// rustAddrMode maps an addressing mode to its AddrMode variant.
func rustAddrMode(m AddressingMode) string {
	switch m {
	case AddrBase:
		return "Base"
	case AddrOffset:
		return "Offset"
	case AddrPre:
		return "PreIndex"
	case AddrPost:
		return "PostIndex"
	default:
		return "Base"
	}
}

func rustTraitName(method string) string {
	parts := strings.Split(method, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	b.WriteString("Args")
	return b.String()
}

// emitFormImpl writes one trait impl: the encoding body for one operand shape.
func emitFormImpl(w *strings.Builder, traitName, method string, f AsmForm, arity int) {
	params := f.Params[:min(arity, len(f.Params))]
	tuple := tupleType(params)

	fmt.Fprintf(w, "// %s: %s\n", f.EncodingID, f.AsmSyntax)
	fmt.Fprintf(w, "impl %s for %s {\n", traitName, tuple)
	w.WriteString("    fn emit_into(self, a: &mut Assembler) {\n")
	bindTupleFields(w, params)

	if len(f.ModeVariants) > 1 {
		// Addressing mode picks the encoding.
		w.WriteString("        match mem.mode {\n")
		for _, v := range f.ModeVariants {
			fmt.Fprintf(w, "            AddrMode::%s => {\n", rustAddrMode(v.Mode))
			emitEncodeBody(w, method, v.FixedWord, v.Placements, params, f.Enums, "                ")
			w.WriteString("            }\n")
		}
		fmt.Fprintf(w, "            m => a.record(AsmError::AddrMode { insn: %q, mode: m }),\n", method)
		w.WriteString("        }\n")
	} else {
		pl := f.Placements
		fw := f.FixedWord
		if len(f.ModeVariants) == 1 {
			pl = f.ModeVariants[0].Placements
			fw = f.ModeVariants[0].FixedWord
		}
		emitEncodeBody(w, method, fw, pl, params, f.Enums, "        ")
	}
	w.WriteString("    }\n}\n\n")
}

// emitCoercionImpl writes a forwarding impl that converts one or more operands
// to the types the canonical impl expects.
func emitCoercionImpl(w *strings.Builder, traitName string, params []Param, variant []string) {
	fmt.Fprintf(w, "impl %s for %s {\n", traitName, tupleOf(variant))
	w.WriteString("    fn emit_into(self, a: &mut Assembler) {\n")
	bindTupleFields(w, params)
	fwd := make([]string, 0, len(params))
	for i, p := range params {
		if i < len(variant) && variant[i] != p.RustType {
			// Label takes a byte offset; register-or-SP positions take the
			// plain register of the same width.
			if p.RustType == "Label" {
				if variant[i] == "LabelId" {
					fwd = append(fwd, fmt.Sprintf("Label::from(%s)", p.Name))
				} else {
					fwd = append(fwd, fmt.Sprintf("Label::Offset(%s)", p.Name))
				}
			} else {
				fwd = append(fwd, fmt.Sprintf("%s::from(%s)", p.RustType, p.Name))
			}
			continue
		}
		fwd = append(fwd, p.Name)
	}
	inner := strings.Join(fwd, ", ")
	if len(fwd) == 1 {
		inner += ","
	}
	fmt.Fprintf(w, "        %s::emit_into((%s), a)\n", traitName, inner)
	w.WriteString("    }\n}\n\n")
}

// emitEncodeBody writes the word construction for one encoding.
func emitEncodeBody(w *strings.Builder, method string, fixed uint32, placements []Placement, params []Param, enums []EnumDispatch, ind string) {
	decl := "let w"
	if encodeBodyMutates(placements, params, enums) {
		decl = "let mut w"
	}
	fmt.Fprintf(w, "%s%s: u32 = 0x%08X;\n", ind, decl, fixed)
	emitArrangementDispatch(w, method, params, ind)
	emitEnumDispatch(w, method, params, enums, ind)
	for _, p := range placements {
		if !placementReachable(p, params) {
			// The operand is omitted at this arity. ARM often specifies what the
			// field holds in that case — RET's Rn defaults to X30 — and leaving
			// it zero would silently encode `ret x0`.
			if p.HasDefault {
				emitFieldBits(w, method, p, fmt.Sprintf("%d", p.Default), p.Field+" default", ind)
			}
			continue
		}
		if p.Xor != 0 {
			fmt.Fprintf(w, "%sw |= ((%s ^ 0x%X) & 0x%X) << %d;\n",
				ind, p.Param, p.Xor, mask(p.Width), p.Start)
			continue
		}
		switch {
		case p.Param == "mem.base.raw()":
			fmt.Fprintf(w, "%sw |= (mem.base.raw() & 0x%X) << %d;\n", ind, mask(p.Width), p.Start)
		case p.Param == "mem.offset":
			emitFieldBits(w, method, p, "mem.offset", "offset", ind)
		case isLabelPlacement(p, params):
			fmt.Fprintf(w, "%sw = a.field_label(w, %s.into(), %d, %d, 4, %q);\n",
				ind, p.Param, p.Start, p.Width, method)
		case isShiftPlacement(p, params):
			fmt.Fprintf(w, "%sw |= (%s.kind() & 0x%X) << %d;\n", ind, p.Param, mask(p.Width), p.Start)
		case isExtendPlacement(p, params):
			fmt.Fprintf(w, "%sw |= ((%s as u32) & 0x%X) << %d;\n", ind, p.Param, mask(p.Width), p.Start)
		case len(p.RegRanges) > 0:
			emitMappedRegister(w, method, p, ind)
		case needsValueCheck(p, params):
			// A split value, a biased register bank, or a register ARM restricts
			// to part of its bank: all need the range check and the multi-field
			// distribution rather than a mask and a shift.
			emitFieldBits(w, method, p, p.Param+" as i64", p.Param, ind)
		case strings.HasSuffix(p.Param, ".raw()"), strings.HasSuffix(p.Param, " as u32"):
			fmt.Fprintf(w, "%sw |= (%s & 0x%X) << %d;\n", ind, p.Param, mask(p.Width), p.Start)
		default:
			emitFieldBits(w, method, p, p.Param+" as i64", p.Param, ind)
		}
	}
	fmt.Fprintf(w, "%sa.emit(w);\n", ind)
}

func emitMappedRegister(w *strings.Builder, method string, p Placement, ind string) {
	local := "mapped_" + placementBase(p)
	fmt.Fprintf(w, "%slet %s: i64 = match %s as i64 {\n", ind, local, p.Param)
	for _, r := range p.RegRanges {
		fmt.Fprintf(w, "%s    v @ %d..=%d => v - %d,\n", ind, r.Lo, r.Hi, r.Bias)
	}
	fmt.Fprintf(w, "%s    _ => { a.record(AsmError::Operand { insn: %q, operand: %q }); return; }\n",
		ind, method, placementBase(p))
	fmt.Fprintf(w, "%s};\n", ind)
	mapped := p
	mapped.Param = local
	mapped.RegRanges = nil
	mapped.Bias = 0
	mapped.Scale = 1
	mapped.HasRange = true
	mapped.Lo = 0
	mapped.Hi = (int64(1) << uint(mapped.Width)) - 1
	emitFieldBits(w, method, mapped, local, placementBase(p), ind)
}

// encodeBodyMutates reports whether the generated body writes its base word.
// Fixed-only encodings still emit the word, but declaring it mutable makes a
// warning-free generated crate impossible under `-D warnings`.
func encodeBodyMutates(placements []Placement, params []Param, enums []EnumDispatch) bool {
	for _, prm := range params {
		if d := prm.ArrDispatch; d != nil && d.Mask&^d.Shared != 0 {
			return true
		}
	}
	for _, d := range enums {
		if paramPresent(d.Param, params) || d.HasDefault {
			return true
		}
	}
	for _, p := range placements {
		if placementReachable(p, params) || p.HasDefault {
			return true
		}
	}
	return false
}

// emitFieldBits writes one range-checked placement, spanning several fields when
// ARM states the value is their concatenation.
func emitFieldBits(w *strings.Builder, method string, p Placement, expr, operand, ind string) {
	lo, hi := placementRange(p)
	fmt.Fprintf(w, "%sw = a.field_bits(w, %s, &[%s], %d, %d, %d, %d, %d, %q, %q);\n",
		ind, expr, partsLiteral(p), scaleOf(p), p.Bias, p.Negate, lo, hi, method, operand)
}

// partsLiteral renders a placement's fields as (start, width) pairs, most
// significant first.
func partsLiteral(p Placement) string {
	if len(p.Parts) == 0 {
		return fmt.Sprintf("(%d, %d, 0)", p.Start, p.Width)
	}
	out := make([]string, 0, len(p.Parts))
	for _, part := range p.Parts {
		if part.IsLit {
			// A negative start marks bits the value must contain rather than
			// bits to write: nothing in the word holds them.
			var v uint32
			for _, ch := range part.Literal {
				v <<= 1
				if ch == '1' {
					v |= 1
				}
			}
			out = append(out, fmt.Sprintf("(-1, %d, %d)", part.Width, v))
			continue
		}
		out = append(out, fmt.Sprintf("(%d, %d, 0)", part.Start, part.Width))
	}
	return strings.Join(out, ", ")
}

// needsValueCheck reports whether a placement must go through the checked path.
func needsValueCheck(p Placement, params []Param) bool {
	// Scale matters even for a register: a multi-vector group base is written
	// Z4 and held as 2, so masking the register number in place would encode
	// twice the intended register with no error.
	if len(p.Parts) > 0 || len(p.RegRanges) > 0 || p.Bias != 0 || p.Negate != 0 || p.Scale > 1 {
		return true
	}
	// A register bank ARM narrows (predicate P0-P7, ZA tile ZA0-ZA3) must be
	// checked: masking would silently alias P8 onto P0.
	return p.HasRange && registerClass(paramClassOf(p, params))
}

// placementReachable drops placements for operands the chosen arity omits.
func placementReachable(p Placement, params []Param) bool {
	if p.Param == "mem.base.raw()" || p.Param == "mem.offset" {
		for _, prm := range params {
			if prm.RustType == "Mem" {
				return true
			}
		}
		return false
	}
	base := placementBase(p)
	for _, prm := range params {
		if prm.Name == base {
			return true
		}
	}
	return false
}

func placementBase(p Placement) string {
	s := strings.TrimSuffix(p.Param, " as i64")
	s = strings.TrimSuffix(s, " as u32")
	s = strings.TrimSuffix(s, ".reg.raw()")
	return strings.TrimSuffix(s, ".raw()")
}

func isLabelPlacement(p Placement, params []Param) bool {
	return paramClassOf(p, params) == ClassLabel
}

func isShiftPlacement(p Placement, params []Param) bool {
	return paramClassOf(p, params) == ClassShift
}

func isExtendPlacement(p Placement, params []Param) bool {
	return paramClassOf(p, params) == ClassExtend
}

func paramClassOf(p Placement, params []Param) OperandClass {
	base := placementBase(p)
	for _, prm := range params {
		if prm.Name == base {
			return prm.Class
		}
	}
	return ClassUnsupported
}

func placementRange(p Placement) (int64, int64) {
	if p.HasRange {
		return p.Lo, p.Hi
	}
	if p.Signed {
		bound := int64(1) << uint(p.Width-1)
		return -bound * scaleOf(p), (bound - 1) * scaleOf(p)
	}
	return 0, ((int64(1) << uint(p.Width)) - 1) * scaleOf(p)
}

func scaleOf(p Placement) int64 {
	if p.Scale < 1 {
		return 1
	}
	return p.Scale
}

func mask(width int) uint32 {
	if width >= 32 || width <= 0 {
		return 0xFFFFFFFF
	}
	return uint32(1)<<uint(width) - 1
}

// tupleType renders the impl's Self type. A one-operand shape uses a 1-tuple so
// every arity is handled uniformly.
func tupleType(params []Param) string {
	if len(params) == 0 {
		return "()"
	}
	ts := make([]string, 0, len(params))
	for _, p := range params {
		ts = append(ts, p.RustType)
	}
	if len(ts) == 1 {
		return "(" + ts[0] + ",)"
	}
	return "(" + strings.Join(ts, ", ") + ")"
}

// bindTupleFields destructures self into named locals so the encoding body reads
// like the ARM syntax.
func bindTupleFields(w *strings.Builder, params []Param) {
	if len(params) == 0 {
		return
	}
	names := make([]string, 0, len(params))
	for _, p := range params {
		names = append(names, p.Name)
	}
	if len(names) == 1 {
		fmt.Fprintf(w, "        let (%s,) = self;\n", names[0])
		return
	}
	fmt.Fprintf(w, "        let (%s) = self;\n", strings.Join(names, ", "))
}

// emitMethod writes the public Assembler method that forwards into the trait.
func emitMethod(w *strings.Builder, method, traitName string, f AsmForm, arity int) {
	params := f.Params[:min(arity, len(f.Params))]

	fmt.Fprintf(w, "    /// `%s`\n", f.AsmSyntax)
	if len(f.ModeVariants) > 1 {
		w.WriteString("    ///\n    /// Addressing mode selects the encoding: ")
		var ms []string
		for _, v := range f.ModeVariants {
			ms = append(ms, string(v.Mode))
		}
		fmt.Fprintf(w, "%s.\n", strings.Join(ms, ", "))
	}

	if len(params) == 0 {
		fmt.Fprintf(w, "    pub fn %s(&mut self) {\n        <() as %s>::emit_into((), self)\n    }\n\n", method, traitName)
		return
	}
	// One generic per operand with a tuple bound. Every arity uses the same
	// shape: a concrete Into<T> would pin the method to one form's types and
	// make the mnemonic's other operand shapes uncallable.
	var generics, args, names []string
	for i, p := range params {
		g := fmt.Sprintf("T%d", i)
		generics = append(generics, g)
		args = append(args, fmt.Sprintf("%s: %s", p.Name, g))
		names = append(names, p.Name)
	}
	tupleGenerics := strings.Join(generics, ", ")
	tupleArgs := strings.Join(names, ", ")
	if len(generics) == 1 {
		tupleGenerics += ","
		tupleArgs += ","
	}
	fmt.Fprintf(w, "    pub fn %s<%s>(&mut self, %s)\n    where\n        (%s): %s,\n    {\n        %s::emit_into((%s), self)\n    }\n\n",
		method, strings.Join(generics, ", "), strings.Join(args, ", "),
		tupleGenerics, traitName, traitName, tupleArgs)
}

// enumVariantIdent renders one ARM value-table spelling as a Rust variant name.
// Spellings include "PLDL1KEEP", "VL1", "#0", "MUL4", "8B" and "S".
func enumVariantIdent(sym string) string {
	var b strings.Builder
	upper := true
	for _, r := range sym {
		switch {
		case r >= 'a' && r <= 'z':
			if upper {
				b.WriteRune(r - 32)
			} else {
				b.WriteRune(r)
			}
			upper = false
		case r >= 'A' && r <= 'Z':
			if upper {
				b.WriteRune(r)
			} else {
				b.WriteRune(r + 32)
			}
			upper = false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			upper = false
		default:
			upper = true
		}
	}
	out := b.String()
	if out == "" {
		return "None"
	}
	if out[0] >= '0' && out[0] <= '9' {
		return "N" + out
	}
	return out
}

// emitEnumTypes renders the operand types ARM defines by a table of assembler
// spellings: prefetch operations, SVE count patterns, slice directions.
func emitEnumTypes(s *AsmSurface) string {
	names := make([]string, 0, len(s.Enums))
	for n := range s.Enums {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	for _, n := range names {
		spec := s.Enums[n]
		// Variant names are derived, so two spellings can collapse onto one
		// identifier; keep the first and drop the rest rather than emitting a
		// duplicate variant that would not compile.
		seen := map[string]bool{}
		var rows []ArrRow
		for _, r := range spec.Rows {
			id := enumVariantIdent(r.Symbol)
			if seen[id] {
				continue
			}
			seen[id] = true
			rows = append(rows, r)
		}
		fmt.Fprintf(&b, "/// `%s` operand, spelled as ARM defines it in the \"%s\" field.\n",
			n, strings.Join(spec.Fields, ":"))
		fmt.Fprintf(&b, "#[derive(Copy, Clone, PartialEq, Eq, Debug)]\npub enum %s {\n", n)
		for _, r := range rows {
			fmt.Fprintf(&b, "    /// `%s`\n    %s,\n", r.Symbol, enumVariantIdent(r.Symbol))
		}
		b.WriteString("}\n\n")
		fmt.Fprintf(&b, "impl core::fmt::Display for %s {\n    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n        let s = match self {\n", n)
		for _, r := range rows {
			fmt.Fprintf(&b, "            %s::%s => %q,\n", n, enumVariantIdent(r.Symbol), r.Symbol)
		}
		b.WriteString("        };\n        f.write_str(s)\n    }\n}\n\n")
	}
	return b.String()
}

// emitRustExact renders one field-level encoder per ARM encoding.
//
// This is what makes the crate complete rather than merely broad: every encoding
// in the spec gets a named function that ORs its settable fields over its fixed
// word, whether or not its operands could be given a friendlier signature. The
// operand-typed methods are a convenience layer over the same encodings.
func emitRustExact(s *AsmSurface) string {
	var b strings.Builder
	b.WriteString("// Generated by mkasm — do not edit.\n//\n")
	b.WriteString("// One exact encoder per ARM encoding: the complete instruction set at field\n")
	b.WriteString("// level. Parameters are the encoding's settable fields, in bit order from the\n")
	b.WriteString("// top of the word, each checked against its width.\n\n")
	b.WriteString("#![allow(clippy::too_many_arguments)]\n\n")
	b.WriteString("use crate::asm_support::{Assembler, AsmError};\n\n")

	typed := 0
	for _, e := range s.Exact {
		if e.Typed {
			typed++
		}
	}
	fmt.Fprintf(&b, "/// How many encodings this crate covers exactly.\npub const ENCODING_COUNT: usize = %d;\n\n", len(s.Exact))
	fmt.Fprintf(&b, "/// How many also have an operand-typed method on [`Assembler`].\npub const TYPED_ENCODING_COUNT: usize = %d;\n\n", typed)

	b.WriteString("impl Assembler {\n")
	for _, e := range s.Exact {
		fmt.Fprintf(&b, "    /// `%s`\n", e.AsmSyntax)
		fmt.Fprintf(&b, "    ///\n    /// ARM encoding `%s`, pattern `%s`.\n", e.EncodingID, e.Pattern)
		if !e.Typed {
			b.WriteString("    ///\n    /// This encoding has no operand-typed method: ARM's description of its\n    /// operands does not place them without guessing.\n")
		}
		// Field names normalise to Rust identifiers, and two ARM fields can
		// normalise to the same one, so names are allocated uniquely.
		used := map[string]bool{}
		names := make([]string, 0, len(e.Fields))
		var args []string
		for _, f := range e.Fields {
			n := uniqueName(fieldParamName(f.Name), used)
			names = append(names, n)
			args = append(args, fmt.Sprintf("%s: u32", n))
		}
		fmt.Fprintf(&b, "    pub fn %s(&mut self%s) {\n", e.Fn, prefixComma(args))
		decl := "let w: u32"
		if len(e.Fields) > 0 {
			decl = "let mut w: u32"
		}
		fmt.Fprintf(&b, "        %s = 0x%08X;\n", decl, e.FixedWord)
		for i, f := range e.Fields {
			// The parameter occupies the bits this encoding leaves free, which do
			// not always start at the field's low bit: MOVI's 16-bit shifted form
			// pins three of cmode's four bits and leaves only bit 13. Shifting by
			// the field start instead would drop the value into the pinned bits
			// and encode a different instruction.
			shift := freeLowBit(f.Free, f.Start)
			// A value that does not fit those bits is reported rather than
			// truncated: silently dropping a field's high bits is the one failure
			// mode a caller cannot detect.
			fmt.Fprintf(&b, "        if ((%s as u64) << %d) & !0x%08Xu64 != 0 {\n", names[i], shift, f.Free)
			fmt.Fprintf(&b, "            self.record(AsmError::Range { insn: %q, operand: %q, value: %s as i64, lo: 0, hi: 0x%X });\n",
				e.EncodingID, f.Name, names[i], f.Free>>uint(shift))
			b.WriteString("            return;\n        }\n")
			fmt.Fprintf(&b, "        w = (w & !0x%08Xu32) | ((%s << %d) & 0x%08X);\n",
				f.Free, names[i], shift, f.Free)
		}
		b.WriteString("        self.emit(w);\n    }\n\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// freeLowBit is the position of a field's lowest settable bit, or the field's
// own start when the encoding pins nothing in it.
func freeLowBit(free uint32, start int) int {
	if free == 0 {
		return start
	}
	n := 0
	for free&1 == 0 {
		free >>= 1
		n++
	}
	return n
}

func prefixComma(args []string) string {
	if len(args) == 0 {
		return ""
	}
	return ", " + strings.Join(args, ", ")
}

// fieldParamName turns an ARM field name into a Rust identifier.
func fieldParamName(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + 32)
		default:
			b.WriteByte('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		out = "f"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "f" + out
	}
	if isRustKeyword(out) {
		out += "_"
	}
	return out
}

// emitRustRaw exposes every encoding the typed surface cannot express, so no
// instruction is unreachable from the crate.
func emitRustRaw(s *AsmSurface) string {
	var b strings.Builder
	b.WriteString("// Generated by mkasm — do not edit.\n//\n")
	b.WriteString("// Field-level emitters for encodings without a typed signature: SVE and SME\n")
	b.WriteString("// predication, register lists, element indices. Every encoding in the ISA is\n")
	b.WriteString("// reachable here even when its operands are not yet typed.\n\n")
	b.WriteString("use crate::asm_support::Assembler;\n\n")
	b.WriteString("/// One settable bit field of a raw encoding.\n")
	b.WriteString("#[derive(Copy, Clone, Debug)]\npub struct RawField {\n    pub name: &'static str,\n    pub start: u8,\n    pub end: u8,\n    /// Absolute word bits this encoding leaves settable inside the field.\n    pub free: u32,\n}\n\n")
	b.WriteString("/// An encoding reachable only by field values.\n")
	b.WriteString("#[derive(Copy, Clone, Debug)]\npub struct RawEncoding {\n    pub encoding_id: &'static str,\n    pub mnemonic: &'static str,\n    pub asm: &'static str,\n    pub fixed_word: u32,\n    pub pattern: &'static str,\n    pub fields: &'static [RawField],\n}\n\n")

	fmt.Fprintf(&b, "/// Every encoding without a typed method (%d of them).\n", len(s.Raw))
	b.WriteString("pub static RAW: &[RawEncoding] = &[\n")
	for _, r := range s.Raw {
		var fs []string
		for _, f := range r.Fields {
			fs = append(fs, fmt.Sprintf("RawField { name: %s, start: %d, end: %d, free: 0x%08X }",
				rustStringLiteral(f.Name), f.Start, f.End, f.Free))
		}
		lit := "&[]"
		if len(fs) > 0 {
			lit = "&[" + strings.Join(fs, ", ") + "]"
		}
		fmt.Fprintf(&b, "    RawEncoding { encoding_id: %s, mnemonic: %s, asm: %s, fixed_word: 0x%08X, pattern: %s, fields: %s },\n",
			rustStringLiteral(r.EncodingID), rustStringLiteral(r.Mnemonic),
			rustStringLiteral(r.AsmSyntax), r.FixedWord, rustStringLiteral(r.Pattern), lit)
	}
	b.WriteString("];\n\n")

	b.WriteString(`/// Looks up a raw encoding by its ARM encoding id.
pub fn raw(encoding_id: &str) -> Option<&'static RawEncoding> {
    RAW.iter().find(|e| e.encoding_id == encoding_id)
}

impl Assembler {
    /// Emits an encoding by id, setting named fields. Unknown ids and unknown
    /// field names are errors, so a typo cannot silently emit a wrong word.
    pub fn emit_raw(&mut self, encoding_id: &str, fields: &[(&str, u32)]) -> Result<(), String> {
        let enc = raw(encoding_id).ok_or_else(|| format!("unknown encoding {encoding_id}"))?;
        let mut w = enc.fixed_word;
        for &(name, value) in fields {
            let f = enc
                .fields
                .iter()
                .find(|f| f.name == name)
                .ok_or_else(|| format!("{encoding_id}: unknown field {name}"))?;
            let width = (f.end - f.start + 1) as u32;
            let max = if width >= 32 { u32::MAX } else { (1u32 << width) - 1 };
            if value > max {
                return Err(format!(
                    "{encoding_id}.{name} = {value} does not fit in {width} bits"
                ));
            }
            let mask = max << f.start;
            let placed = value << f.start;
            let pinned = mask & !f.free;
            if pinned != 0 && (placed & pinned) != (w & pinned) {
                return Err(format!(
                    "{encoding_id}.{name} = {value} conflicts with pinned bits"
                ));
            }
            w = (w & !f.free) | (placed & f.free);
        }
        self.emit(w);
        Ok(())
    }
}
`)
	return b.String()
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// arrangementIdent renders an ARM arrangement spelling as a Rust variant name.
// ARM writes the lane count first ("8B"); Rust identifiers cannot, so the count
// moves to the end ("B8").
func arrangementIdent(sym string) string {
	digits := ""
	letters := ""
	for _, r := range sym {
		if r >= '0' && r <= '9' {
			digits += string(r)
			continue
		}
		letters += strings.ToUpper(string(r))
	}
	if letters == "" {
		return "A" + digits
	}
	return letters + digits
}

// emitArrangementEnum renders every arrangement spelling the spec uses, plus the
// register types that carry one.
func emitArrangementEnum(s *AsmSurface) string {
	seen := map[string]bool{}
	var syms []string
	for _, name := range s.MethodOrder {
		for _, f := range s.Methods[name] {
			for _, d := range f.Arrangements {
				for _, c := range d.Cases {
					if !seen[c.Symbol] {
						seen[c.Symbol] = true
						syms = append(syms, c.Symbol)
					}
				}
			}
		}
	}
	sort.Strings(syms)

	var b strings.Builder
	b.WriteString("/// Element arrangement of a vector operand, as ARM spells it.\n")
	b.WriteString("#[derive(Copy, Clone, PartialEq, Eq, Debug)]\npub enum Arrangement {\n")
	for _, sym := range syms {
		fmt.Fprintf(&b, "    /// `%s`\n    %s,\n", sym, arrangementIdent(sym))
	}
	b.WriteString("}\n\nimpl core::fmt::Display for Arrangement {\n")
	if len(syms) == 0 {
		// A partial generate can resolve no arrangements at all. The enum is then
		// uninhabited, and only an empty match over the value is well typed.
		b.WriteString("    fn fmt(&self, _f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n        match *self {}\n    }\n}\n\n")
		return b.String() + emitSizedOperandTypes(syms)
	}
	b.WriteString("    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n        let s = match self {\n")
	for _, sym := range syms {
		fmt.Fprintf(&b, "            Arrangement::%s => %q,\n", arrangementIdent(sym), sym)
	}
	b.WriteString("        };\n        f.write_str(s)\n    }\n}\n\n")

	return b.String() + emitSizedOperandTypes(syms)
}

// emitSizedOperandTypes renders the operand types that pair a register with the
// element arrangement it is used at, plus one constructor per legal spelling.
func emitSizedOperandTypes(syms []string) string {
	var b strings.Builder
	for _, pair := range [][2]string{{"VecOp", "VReg"}, {"ZOp", "ZReg"}, {"POp", "PReg"}, {"PnOp", "PnReg"}, {"ZaOp", "ZaTile"}} {
		op, reg := pair[0], pair[1]
		fmt.Fprintf(&b, "/// A `%s` together with the element arrangement it is used at.\n", reg)
		fmt.Fprintf(&b, "#[derive(Copy, Clone, PartialEq, Eq, Debug)]\npub struct %s {\n    pub reg: %s,\n    pub arr: Arrangement,\n}\n\n", op, reg)
		fmt.Fprintf(&b, "impl %s {\n    /// Sizes this register, as in `V0.arr(Arrangement::B8)` for `v0.8b`.\n    pub const fn arr(self, arr: Arrangement) -> %s {\n        %s { reg: self, arr }\n    }\n", reg, op, op)
		for _, sym := range syms {
			fmt.Fprintf(&b, "    /// `.%s`\n    pub const fn %s(self) -> %s {\n        %s { reg: self, arr: Arrangement::%s }\n    }\n",
				strings.ToLower(sym), strings.ToLower(arrangementIdent(sym)), op, op, arrangementIdent(sym))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// emitArrangementDispatch writes the matches that turn operand arrangements into
// encoding bits.
//
// Operands sized by different specifiers are not equal but are correlated: in
// ADDHNB <Zd>.<T>, <Zn>.<Tb> both specifiers are tables over the same size
// field, so the arrangements agree exactly when they select the same bits.
// Comparing the selected bits is the correct check; comparing the spellings
// would reject every narrowing and reduction instruction.
// Two specifiers may also only partly overlap: SADDLV <V><d>, <Vn>.<T> sizes
// the destination from "size" alone and the source from "size:Q", so they must
// agree on "size" while <T> alone contributes "Q".
func emitArrangementDispatch(w *strings.Builder, method string, params []Param, ind string) {
	for _, prm := range params {
		if prm.ArrDispatch == nil {
			continue
		}
		d := prm.ArrDispatch
		local := "arr_" + prm.Name

		fmt.Fprintf(w, "%slet %s: u32 = match %s.arr {\n", ind, local, prm.Name)
		for _, c := range d.Cases {
			fmt.Fprintf(w, "%s    Arrangement::%s => 0x%08X,\n", ind, arrangementIdent(c.Symbol), c.Or)
		}
		fmt.Fprintf(w, "%s    other => { a.record(AsmError::Arrangement { insn: %q, arr: other }); return; }\n", ind, method)
		fmt.Fprintf(w, "%s};\n", ind)

		if d.Shared != 0 && d.Lead != "" {
			fmt.Fprintf(w, "%sif %s & 0x%08X != %s & 0x%08X { a.record(AsmError::ArrangementMismatch { insn: %q }); return; }\n",
				ind, local, d.Shared, d.Lead, d.Shared, method)
		}
		if own := d.Mask & ^d.Shared; own != 0 {
			fmt.Fprintf(w, "%sw &= !0x%08Xu32;\n", ind, own)
			fmt.Fprintf(w, "%sw |= %s & 0x%08X;\n", ind, local, own)
		}
	}
}

// emitEnumDispatch writes the match that turns an enumerated operand's spelling
// into encoding bits. The enum type is shared across instructions, so a spelling
// this encoding does not define is an error rather than an unreachable arm.
func emitEnumDispatch(w *strings.Builder, method string, params []Param, enums []EnumDispatch, ind string) {
	for _, d := range enums {
		if !paramPresent(d.Param, params) {
			if d.HasDefault {
				fmt.Fprintf(w, "%sw &= !0x%08Xu32;\n", ind, d.Mask)
				fmt.Fprintf(w, "%sw |= 0x%08Xu32;\n", ind, d.DefaultOr)
			}
			continue
		}
		fmt.Fprintf(w, "%slet sel_%s: u32 = match %s {\n", ind, d.Param, d.Param)
		for _, c := range d.Cases {
			fmt.Fprintf(w, "%s    %s::%s => 0x%08X,\n", ind, d.Type, enumVariantIdent(c.Symbol), c.Or)
		}
		if !d.Exhaustive {
			fmt.Fprintf(w, "%s    _ => { a.record(AsmError::Operand { insn: %q, operand: %q }); return; }\n",
				ind, method, d.Param)
		}
		fmt.Fprintf(w, "%s};\n", ind)
		fmt.Fprintf(w, "%sw &= !0x%08Xu32;\n", ind, d.Mask)
		fmt.Fprintf(w, "%sw |= sel_%s;\n", ind, d.Param)
	}
}

func paramPresent(name string, params []Param) bool {
	for _, p := range params {
		if p.Name == name {
			return true
		}
	}
	return false
}
