package arm

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// GoConformanceCase identifies one generated exact-encoder call.
type GoConformanceCase struct {
	EncodingID string
	Fields     []GoConformanceField
}

// GoConformanceField is one complete field value passed to EncodeWithFields.
type GoConformanceField struct {
	Name  string
	Value uint64
}

// GoConformanceCases builds one deterministic, non-zero exact-encoder sample
// for every encoding in catalog. Values include each field's pinned bits and
// vary only bits the encoding actually leaves writable.
func GoConformanceCases(catalog *Catalog) []GoConformanceCase {
	return GoConformanceCasesFor(catalog, nil)
}

// GoConformanceCasesFor builds exact-encoder probes and, when supplied, uses
// the print model to choose architecturally legal representatives.
func GoConformanceCasesFor(catalog *Catalog, disasm *DisasmSurface) []GoConformanceCase {
	if catalog == nil {
		return nil
	}
	forms := conformanceForms(disasm)
	cases := make([]GoConformanceCase, 0, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		if !entry.HasFixed {
			continue
		}
		word := entry.FixedWord
		for i, field := range entry.Fields {
			if field.Fixed || field.Name == "" || field.Free == 0 {
				continue
			}
			low := freeLowBit(field.Free, field.Start)
			variable := (uint32(i*7+1) << uint(low)) & field.Free
			if variable == 0 {
				variable = field.Free & (^field.Free + 1)
			}
			word = word&^field.Free | variable
		}
		word = legalConformanceWord(word, entry.Mask, entry.Value, forms[entry.EncodingID])

		c := GoConformanceCase{EncodingID: entry.EncodingID}
		for _, field := range entry.Fields {
			if field.Fixed || field.Name == "" || field.Free == 0 {
				continue
			}
			fieldMask := fieldRangeMask(field.Start, field.End)
			full := (word & fieldMask) >> uint(field.Start)
			c.Fields = append(c.Fields, GoConformanceField{Name: field.Name, Value: uint64(full)})
		}
		cases = append(cases, c)
	}
	return cases
}

// EmitGoConformanceTest emits the generated module's exact-encoder ledger.
//
// Ordinary `go test ./...` skips the ledger. The strict external gate enables
// it, parses "<index>\t<encoding-id>\t<word>", renders each word from the ARM
// print model, and requires LLVM to reproduce the same bytes.
func EmitGoConformanceTest(modulePath string, catalog *Catalog) (string, []GoConformanceCase) {
	return EmitGoConformanceTestFor(modulePath, catalog, nil)
}

func EmitGoConformanceTestFor(
	modulePath string,
	catalog *Catalog,
	disasm *DisasmSurface,
) (string, []GoConformanceCase) {
	cases := GoConformanceCasesFor(catalog, disasm)
	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by mkasm. DO NOT EDIT.

package conformance

import (
	"fmt"
	"os"
	"testing"

	%q
)

var exactConformanceCases = []struct {
	id     string
	fields map[string]uint64
}{
`, modulePath+"/encoders")
	for _, c := range cases {
		fmt.Fprintf(&b, "\t{%q, map[string]uint64{", c.EncodingID)
		for i, field := range c.Fields {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q: %d", field.Name, field.Value)
		}
		b.WriteString("}},\n")
	}
	fmt.Fprintf(&b, `}

func TestExactConformanceWords(t *testing.T) {
	if os.Getenv("MKASM_GO_CONFORMANCE_LEDGER") != "1" {
		t.Skip("set MKASM_GO_CONFORMANCE_LEDGER=1; the ledger is consumed by the external LLVM gate")
	}
	for i, c := range exactConformanceCases {
		word, err := encoders.EncodeWithFields(c.id, c.fields)
		if err != nil {
			t.Fatalf("%%s: %%v", c.id, err)
		}
		fmt.Printf("%%d\t%%s\t%%08X\n", i, c.id, word)
	}
`)
	fmt.Fprintf(&b, "\t// %d exact encoders emitted for external byte verification.\n}\n", len(cases))

	src := b.String()
	if formatted, err := format.Source([]byte(src)); err == nil {
		src = string(formatted)
	}
	return src, cases
}

func writeGoConformanceTest(
	outputDir, modulePath string,
	catalog *Catalog,
	disasm *DisasmSurface,
) error {
	src, cases := EmitGoConformanceTestFor(modulePath, catalog, disasm)
	if len(cases) == 0 {
		return fmt.Errorf("go codegen: no exact conformance calls")
	}
	dir := filepath.Join(outputDir, "conformance")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "conformance_test.go"), []byte(src), 0644)
}
