package arm

import (
	"fmt"
	"strings"
)

// RustConformanceCase identifies one actual generated typed-method call in the
// source returned by EmitRustConformanceTest.
type RustConformanceCase struct {
	EncodingID string
	Method     string
}

// EmitRustConformanceTest emits an ignored Rust integration test that calls every typed
// assembler implementation with the same justified non-zero samples used by
// the generated unit tests. Each call gets a fresh Assembler so its one output
// word can be attributed without state leaking between instructions.
//
// The returned program prints "<index>\t<encoding-id>\t<word>" per call.
// External conformance tooling can render and assemble those words with an
// independent toolchain, then compare the bytes.
//
// The test is ignored during an ordinary `cargo test` because producing the
// call ledger is only the first half of conformance. The repository's strict
// LLVM gate runs this test with --ignored, independently assembles every
// printable call, and requires byte-identical output.
func EmitRustConformanceTest(crateName string, s *AsmSurface) (string, []RustConformanceCase) {
	if s == nil {
		return "", nil
	}
	crateIdent := strings.ReplaceAll(crateName, "-", "_")
	var b strings.Builder
	fmt.Fprintf(&b, `// Generated by mkasm — do not edit.
//
// Machine-readable typed-call ledger for the independent LLVM conformance gate.
// Run directly with:
//   cargo test --test conformance typed_conformance_words -- --ignored --nocapture
//
// A passing invocation proves that every generated call emits one word. Full
// byte conformance additionally requires an external assembler to consume this
// ledger; go-mkasm's mise run conformance:rust is the reference oracle driver.

use %s::*;

#[test]
#[ignore = "ledger consumed by the external LLVM conformance gate"]
fn typed_conformance_words() {
`, crateIdent)

	var cases []RustConformanceCase
	for _, name := range s.MethodOrder {
		for _, g := range GroupByArity(name, s.Methods[name]) {
			claimed := map[string]bool{}
			for _, f := range g.Forms {
				f.RequiredArity = g.Arity
				n := g.Arity
				if n > len(f.Params) {
					n = len(f.Params)
				}
				if tuple := tupleType(f.Params[:n]); claimed[tuple] {
					continue
				} else {
					claimed[tuple] = true
				}
				args, ok := sampleArgs(f)
				if !ok {
					continue
				}
				index := len(cases)
				cases = append(cases, RustConformanceCase{
					EncodingID: f.EncodingID,
					Method:     g.Method,
				})
				fmt.Fprintf(&b, `    {
        let mut a = Assembler::new();
        a.%s(%s);
        assert!(a.error().is_none(), %q, a.error());
        assert_eq!(a.words().len(), 1, %q);
        println!("%d\t%s\t{:08X}", a.words()[0]);
    }
`,
					g.Method, args,
					f.EncodingID+": generated call failed: {:?}",
					f.EncodingID+": generated call did not emit exactly one word",
					index, f.EncodingID,
				)
			}
		}
	}
	fmt.Fprintf(&b, "    // %d typed calls emitted for external byte verification.\n", len(cases))
	b.WriteString("}\n")

	return b.String(), cases
}

// EmitRustExactConformanceTest emits one ignored integration-test call for
// every exact encoder in the generated crate. Unlike the typed ledger, this is
// exhaustive over the resolved instruction corpus.
func EmitRustExactConformanceTest(crateName string, s *AsmSurface) (string, []RustConformanceCase) {
	return EmitRustExactConformanceTestFor(crateName, s, nil)
}

func EmitRustExactConformanceTestFor(
	crateName string,
	s *AsmSurface,
	disasm *DisasmSurface,
) (string, []RustConformanceCase) {
	if s == nil {
		return "", nil
	}
	forms := conformanceForms(disasm)
	crateIdent := strings.ReplaceAll(crateName, "-", "_")
	var b strings.Builder
	fmt.Fprintf(&b, `// Generated by mkasm — do not edit.
//
// Exhaustive exact-encoder ledger for the independent LLVM conformance gate.
// Run directly with:
//   cargo test --test exact_conformance exact_conformance_words -- --ignored --nocapture

use %s::*;

#[test]
#[ignore = "ledger consumed by the external LLVM conformance gate"]
fn exact_conformance_words() {
`, crateIdent)

	cases := make([]RustConformanceCase, 0, len(s.Exact))
	for _, exact := range s.Exact {
		word := exact.FixedWord
		var writable uint32
		for i, field := range exact.Fields {
			shift := freeLowBit(field.Free, field.Start)
			value := uint32(i*7+1) & (field.Free >> uint(shift))
			if value == 0 && field.Free != 0 {
				value = 1
			}
			word = word&^field.Free | value<<uint(shift)&field.Free
			writable |= field.Free
		}
		word = legalConformanceWord(word, ^writable, exact.FixedWord, forms[exact.EncodingID])

		args := make([]string, 0, len(exact.Fields))
		for _, field := range exact.Fields {
			shift := freeLowBit(field.Free, field.Start)
			value := word & field.Free >> uint(shift)
			args = append(args, fmt.Sprintf("%d", value))
		}
		index := len(cases)
		cases = append(cases, RustConformanceCase{
			EncodingID: exact.EncodingID,
			Method:     exact.Fn,
		})
		fmt.Fprintf(&b, `    {
        let mut a = Assembler::new();
        a.%s(%s);
        assert!(a.error().is_none(), %q);
        assert_eq!(a.words().len(), 1, %q);
        println!("%d\t%s\t{:08X}", a.words()[0]);
    }
`,
			exact.Fn, strings.Join(args, ", "),
			exact.EncodingID+": generated exact call failed",
			exact.EncodingID+": generated exact call did not emit exactly one word",
			index, exact.EncodingID,
		)
	}
	fmt.Fprintf(&b, "    // %d exact encoders emitted for external byte verification.\n", len(cases))
	b.WriteString("}\n")
	return b.String(), cases
}
